### ISSUE TITLE
Just wondering whether or how "Taiwan" is handled?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [ufbmi/geographical-entity-ontology#1]
I see a treatment of Palestinian Occupied Territories which seems appropriate.  Is "Taiwan" a similarly complicated case?

**Comment by hoganwr** [comment]
I've been looking in the OWL files and for some reason, Taiwan seems to be
missing.  I'm looking at the source data I used to create the OWL files and
don't see Taiwan there either.

I'm going to log an issue on the tracker.  We're pretty busy right now, but
I should have the situation resolved in about two weeks.

In the meantime if you have suggestions on how to handle Taiwan's unique
status (sovereign state vs. dependency), I'm all ears.

**Comment by hoganwr** [comment]
I see this is already logged as an issue.

**Comment by Public-Health-Bioinformatics** [comment]
K, thanks, and no rush.  Taiwan is a tough one.  Just reading wikipedia on it makes my head spin.  Not quite as bad as bangladeshi-Indian 1st/2nd/3rd order enclaves but still a doozie.  No advice to offer!

Damion

**Comment by dillerm** [comment]
After a bit of background research, we've come to the conclusion that Taiwan meets the definition for '_de facto_ sovereign state' (i.e., sovereign state), but does not meet the definition for '_de jure_ sovereign state' (i.e., a state whose sovereignty is acknowledged by the international community, which is the UN). The rationale behind this can be found at GEO's [Wiki](https://github.com/ufbmi/geographical-entity-ontology/wiki/Classification-of-Taiwan).

Our current definition for 'sovereign state', which is borrowed from the Montevideo Convention, refers to _de facto_ state. As such, in order to represent Taiwan, we'll need to create a class for _de jure_ state, which I'll propose a definition for below:

> A sovereign state whose political sovereignty has been recognized by the United Nations, in accordance with international law.

We will then want to move all OWL individuals that currently are rdf:type "sovereign state" to rdf:type "de facto sovereign state." We should also, presumably, add a comment or two to this class that briefly clarifies the process through which a state receives international recognition (i.e., through full membership to the UN), and that this membership supersedes all other claims to that state's sovereignty.

**Comment by hoganwr** [comment]
Just to be clear, all the nation instances in GEO are already rdf:type sovereign state (de facto state).   They all need to be moved to de jure sovereign state.  Then we can add Taiwan and others as de facto states.
